package br.com.souzawebsistemas.enums;

public enum Profissao {
	AUXILIARPRODUCAO("AUXILIAR DE PRODUCAO"),
	ENCARREGADOSETOR("ENCARREGADO DE SETOR"),
	EMPREGADADOMESTICA("EMPREGADA DOM�STICA"),
	PASSADEIRAROUPA("PASSADEIRA DE ROUPA"),
	AUXILIARLIMPEZA("AUXILIAR DE LIMPEZA"),
	PEDREIRO("PEDREIRO"),
	AJUDANTEPEDREIRO("AJUDANTE DE PEDREIRO"),
	PIZZAIOLO("PIZZAIOLO"),
	CHAPEIROLANCHONETE("CHAPEIRO DE LANCHONETE"),
	ENTREGADOR("ENTREGADOR"),
	ELETRICISTA("ELETRICISTA"),
	ENCANADOR("ENCANADOR"),
	MOTORISTA("MOTORISTA"),
	PROGRAMADORJAVADESK("PROGRAMADOR JAVA DESKTOP"),
	PROGRAMADORJAVAWEB("PROGRAMADOR JAVA WEB");
	
	private String descricao;
	private Profissao(String descricao) {
		this.descricao=descricao;
	}
	
}
